-- CreateEnum
CREATE TYPE "ActionsType" AS ENUM ('ENTRAR_NO_SISTEMA_HOME', 'CRIAR_PROVA_HOME', 'VOLTAR_CRIAR_PROVA_FORM', 'LIMPAR_CRIAR_PROVA_FORM', 'CRIAR_CRIAR_PROVA_FORM', 'VOLTAR_EDITE_PROVA', 'GUARDAR_QUESTOES_EDITE_PROVA', 'BUSCAR_MAIS_QUESTOES_EDITE_PROVA', 'CRIAR_QUESTAO_EDITE_PROVA', 'GABARITO_EDITE_PROVA', 'BAIXAR_PROVA_EDITE_PROVA', 'BAIXAR_EM_ORDEM_ALEATORIOA_EDITE_PROVA', 'UP_QUESTAO_EDITE_PROVA', 'DOWN_QUESTAO_EDITE_PROVA', 'EDITE_QUESTAO_EDITE_PROVA', 'DELETE_QUESTAO_EDITE_PROVA', 'CANCELAR_MODAL_EDITE_QUESTAO', 'SALVAR_MODAL_EDITE_QUESTAO', 'CANCELAR_MODAL_CRIAR_QUESTAO', 'SALVAR_MODAL_CRIAR_QUESTAO', 'BUSCAR_MODAL_MAIS_QUESTOES', 'CONCLUIR_MODAL_MAIS_QUESTOES', 'ADD_QUESTAO_MODAL_MAIS_QUESTOES', 'CRIAR_PROVA_EM_BRANCO_HOME', 'CONTRIBUIR_COM_QUESTAO_HOME', 'VOLTAR_CRIAR_QUESTAO_FORM', 'LIMPAR_CRIAR_QUESTAO_FORM', 'SALVAR_CRIAR_QUESTAO_FORM', 'USAR_OUTRO_USUARIO_HOME', 'VOLTAR_CARREGAR_USUARIO', 'CARREGAR_QUESTOES_CARREGAR_USUARIO', 'VER_PROVA_HOME');

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userKey" TEXT NOT NULL,
    "action" "ActionsType" NOT NULL,
    "data" JSONB,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);